### ISSUE TITLE
igraph2mgraph 

### ISSUE THREAD

**Issue by karolceron** [lsaravia/multiweb#2]
Hi Leonardo, 

I've trouble when running:

> gt <- igraph2mgraph(g, c("Negative", "Positive", "Antagonistic"))

Error in igraph2mgraph(g, c("Negative", "Positive", "Antagonistic")) : 
  could not find function "igraph2mgraph

Is this a function from the multiweb package?

**Comment by lsaravia** [comment]
I renamed that function to `fromIgraphToMgraph` and I forgot to update the README with the new name of the function. Fixed in last commit #f730bc8

**Comment by karolceron** [comment]
Thank you!
