### ISSUE TITLE
Request: choose clustering method for topological roles

### ISSUE THREAD

**Issue by ellazd** [lsaravia/multiweb#3]
Hello,

Would it be possible to make a change to the calc_topological_roles function to allow users to select the clustering method from other methods included in igraph for calculating c and z scores?

Cheers

**Comment by lsaravia** [comment]
Updated the function calc_topological_roles to accept a new parameter with the community object so you can use another method and then calculate topological roles.  [f785fb8](https://github.com/lsaravia/multiweb/commit/f785fb8ee2cec58a79a854ffc5776247c01deada)

**Comment by ellazd** [comment]
Great! Thank you
